apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5odWIuZG9ja2VyLmNvbSI6eyJ1c2VybmFtZSI6InZpbGxlcnMiLCJwYXNzd29yZCI6ImVuN203NXpqMDAiLCJlbWFpbCI6InZpbGxlcnMubWlja2FlbEBnbWFpbC5jb20iLCJhdXRoIjoiZG1sc2JHVnljenBsYmpkdE56VjZhakF3In19fQ==
kind: Secret
metadata:
  name: regcred
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: builder-service
secrets:
  - name: regcred