apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tekton-dashboard
  namespace: tekton-pipelines
spec:
  rules:
    - host: tekton-dashboard.127.0.0.1.xip.io
      http:
        paths:
          - backend:
              serviceName: tekton-dashboard
              servicePort: 9097