apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: tekton-services-gateway
  namespace: tekton-pipelines
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http-istio-services
        protocol: HTTP
      hosts:
        - tekton-dashboard.127.0.0.1.xip.io
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tekton-dashboard-virtual-service
  namespace: tekton-pipelines
spec:
  hosts:
    - "tekton-dashboard.127.0.0.1.xip.io"
  gateways:
    - tekton-services-gateway
  http:
    - route:
        - destination:
            host: tekton-dashboard.tekton-pipelines.svc.cluster.local
            port:
              number: 9097
      websocketUpgrade: true
